name: Daily Email to Slack

on:
  schedule:
    # Run daily at 9 PM UTC (10 PM Zurich time)
    - cron: "5 21 * * *"  # Hour:Minute in UTC format

jobs:
  check-emails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run email forwarder script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          python mail_to_slack.py
